import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  buttonCart: {
    borderWidth: 0.5,
    borderColor: "black",
    borderRadius: 10,
    width: 75,
    marginRight: 20,
    textAlign: "center",
    backgroundColor: "yellow",
    fontSize: 20,
    fontWeight: "bold",
  },
  extButtonQty: {
    borderWidth: 0.5,
    borderColor: "black",
    borderRadius: 15,
    width: 30,
    height: 30,
    backgroundColor: "yellow",
    marginRight: 10,
    textAlign: "center",
    paddingTop: 1,
    fontSize: 20,
  },
  midButtonQty: {
    borderWidth: 0.5,
    borderColor: "black",
    borderRadius: 15,
    width: 50,
    height: 30,
    backgroundColor: "yellow",
    marginRight: 10,
    textAlign: "center",
    paddingTop: 1,
    fontSize: 20,
  },
  regButton: {
    width: "80%",
    height: 50,
    backgroundColor: "green",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    marginTop: 20,
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffd4771a",
    paddingTop: 50,
  },
  menuButton: {
    width: "100%",
    height: 160,
    backgroundColor: "#ffd4771a",
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 0.5,
  },
  menuNameText: {
    color: "black",
    fontSize: 20,
    marginTop: 5,
  },
  menuText: {
    color: "black",
    marginLeft: -70,
    marginRight: 5,
    fontSize: 15,
    marginTop: 5,
  },
  containerScontrino: {
    flexDirection: "row",
    width: "90%",
    backgroundColor: "white",
    justifyContent: "space-between",
  },
  containerHeader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffd4771a",
    width: "100%",
  },
});

export default styles;
